# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/68e4c3b7-5fa8-451e-953a-ca366d535685";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/436a1cff-f511-42b6-8ec7-265674c4b091";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F68C-50C5";
      fsType = "vfat";
    };
  fileSystems."/mnt/hdd" =
    { device = "/dev/mapper/hdd";
      fsType = "ext4";
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/be8bb4b2-de0a-49ab-9801-63503181fb8a"; } 
  ];

  nix.maxJobs = lib.mkDefault 4;
}
